
# Name your package! Package names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'parsely'
version: '0.0.1'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!
# In this example config, we tell dbt to build all models in the example/ directory
# as views (the default). Try changing `view` to `table` below, then re-running dbt
models:
  parsely:
    vars:
      'parsely:events': 'parsely_rawdata'
      'parsely:timezone': 'America/New_York'
      'parsely:actions': "('pageview','heartbeat','videostart','vheartbeat')" #or use parsely:actions: ['pageview', 'heartbeat', 'vheartbeat', 'videostart'] and then in a model use: ( {{ var('events') | join(", ") }} )
      'custom:excludebottraffic': 'Yes' #update to 'No' if bot traffic should be included
      'custom:extradata': 'userType' #why does this change to usertype all lowercase when referring to the variable?
      'custom:extradataname': 'publisher_user_type'
      'custom:actions': ''
      'custom:loyaltyuser': '30' #number of pageviews that count a user as loyalty
    base:
#      materialized: ephemeral
      optional:
        enabled: true
    transform:
    pageviews:
    videoviews:
    sessions:
    users:
      materialized: view
    metadata:
      materialized: view
    errors:
    audit:
